version: '3.9'
services:
  # chroma:
  #   container_name: chroma_db
  #   image: chromadb/chroma:0.5.4.dev16
  #   volumes:
  #     - ./index_data:/chroma/chroma   # This is the path to the index data for turboard docs
  #   environment:
  #     IS_PERSISTENT: 'TRUE'
  #     # ALLOW_RESET: 'TRUE'
  #   restart: always

  api:
    container_name: proj0_api
    build: ./api
    image: proj0_api_image
    ports:
      - 580:80
    volumes:
      - ./api:/api
    # depends_on:
    #   - chroma

    environment:
      DEBUG: '1'  # Set to '0' for production
    restart: always



  django:
    container_name: proj0_django
    build: ./django
    image: proj0_django_image
    volumes:
      - ./django:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=secret
      - DJANGO_SETTINGS_MODULE=proj0.settings
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - PYTHONUNBUFFERED=1
      - AI_SERVICE_URL=http://api:80/resumes/


    restart: always

  db:
    image: postgres:16  # Changed from postgres:13 to postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes: # It's highly recommended to use a named volume to persist your data
      - postgres_data:/var/lib/postgresql/data
    restart: always


  redis:
    image: redis:6.2-alpine  # More specific version, alpine for smaller size
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data  # Add persistence
    command: redis-server --appendonly yes  # Enable persistence
    restart: always

volumes:
  redis_data:  # Define volume for persistence
  postgres_data:  # Define volume for persistence