version: '3.9'
services:
  # chroma:
  #   container_name: chroma_db
  #   image: chromadb/chroma:0.5.4.dev16
  #   volumes:
  #     - ./index_data:/chroma/chroma   # This is the path to the index data for turboard docs
  #   environment:
  #     IS_PERSISTENT: 'TRUE'
  #     # ALLOW_RESET: 'TRUE'
  #   restart: always

  api:
    container_name: proj0_api
    build: ./api
    image: proj0_api_image
    ports:
      - 580:80
    volumes:
      - ./api:/api
    # depends_on:
    #   - chroma

    environment:
      DEBUG: '1'  # Set to '0' for production
    restart: always

  mongodb:
    image: mongo:latest # Or a specific version if you prefer (02e.g., mongo:6.0)
    container_name: proj0_mongodb
    restart: always # Restart the container if it crashes
    ports:
      - "27017:27017" # Expose the MongoDB port
    volumes:
      - mongodb_data:/data/db # Persist data across container restarts
    environment:
      MONGO_INITDB_ROOT_USERNAME: mamo # Set a root username (important for security)
      MONGO_INITDB_ROOT_PASSWORD: 123456 # Set a root password (important for security)

volumes:
  mongodb_data: # Define the volume for data persistence