# Generated by Django 5.2.1 on 2025-05-18 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="A name for this resume (e.g., 'Software Engineer Resume')", max_length=100, null=True)),
                ('resume', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, help_text='A brief description about the resume', null=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description about the resume', null=True)),
                ('icon', models.CharField(blank=True, help_text='An icon name for this resume', max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this resume is the default resume')),
                ('other_docs', models.JSONField(blank=True, help_text='Any attachments related to this resume (e.g., cover letter)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('yaml_content', models.TextField(default='')),
                ('json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_website', to='api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_content', models.JSONField(default=dict)),
                ('document_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('recommendation_letter', 'Recommendation Letter'), ('motivation_letter', 'Motivation Letter')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='api.resume')),
            ],
        ),
    ]
