# Generated by Django 5.2.1 on 2025-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='other_docs',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_search_keywords',
            field=models.CharField(blank=True, help_text="Keywords related to job search (e.g., 'Python, Django')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='sections_sort',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of section keys for the resume structure.'),
        ),
    ]
