# Generated by Django 5.2.1 on 2025-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_resume_other_docs_resume_job_search_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hidden_sections',
            field=models.JSONField(blank=True, default=list, help_text='Empty or hidden sections by user'),
        ),
    ]
