# Generated by Django 4.2.17 on 2024-12-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_education_degree_alter_education_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='location',
            name='personal_information',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='personal_information',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='about',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, help_text="A name for this resume (e.g., 'Software Engineer Resume')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AwardsAndRecognition',
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
