# Generated by Django 4.2.17 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_certifications_resume_remove_education_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='data',
        ),
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.TextField(blank=True, help_text='A brief description about the resume', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this resume is the default resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='other_docs',
            field=models.JSONField(blank=True, help_text='Any attachments related to this resume (e.g., cover letter)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
