# Generated by Django 4.2.17 on 2024-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_resume_data_resume_about_resume_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description about the resume', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='icon',
            field=models.CharField(blank=True, help_text='An icon name for this resume', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, help_text="A name for this resume (e.g., 'Software Engineer Resume')", max_length=100, null=True),
        ),
    ]
