# Generated by Django 5.2 on 2025-04-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_generatedwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='yaml_content',
            field=models.TextField(default=''),
        ),
    ]
