# Generated by Django 5.2 on 2025-05-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('cover_letter', 'Cover Letter'), ('recommendation_letter', 'Recommendation Letter'), ('motivation_letter', 'Motivation Letter')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='yaml_content',
            field=models.JSONField(default=dict),
        ),
    ]
