# Generated by Django 5.2.4 on 2025-08-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_backgroundtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedwebsite',
            name='unique_id',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
