# Generated by Django 5.2 on 2025-05-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_generateddocument_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateddocument',
            old_name='yaml_content',
            new_name='json_content',
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='user',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
