# Generated by Django 5.2 on 2025-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_yaml_content_generateddocument_json_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddocument',
            name='user',
        ),
    ]
