# Generated by Django 5.2 on 2025-05-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_generateddocument_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
    ]
