# Generated by Django 5.2 on 2025-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='json_content',
            field=models.JSONField(default=dict),
        ),
    ]
