# Generated by Django 5.2 on 2025-05-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_generatedwebsite_json_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedwebsite',
            name='json_content',
        ),
    ]
