# Generated by Django 5.2 on 2025-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_generatedwebsite_json_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedwebsite',
            name='html_content',
        ),
        migrations.AddField(
            model_name='generatedwebsite',
            name='json_content',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
