# Generated by Django 5.2 on 2025-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_generatedwebsite_html_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedwebsite',
            name='json_content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
