# Specify the base image to use with Python 3.11.12
FROM python:3.11.12-slim-bookworm


# Set the working directory inside the container where the application code will reside
WORKDIR /app

# Install system dependencies required for WeasyPrint and other potential needs
# Update the package lists
RUN apt-get update && \
    # Install necessary packages:
    #   gcc: For compiling Python packages with C extensions (may be needed by some dependencies)
    #   libc6: Basic C runtime libraries (required by many programs)
    #   libffi-dev: Development files for the Foreign Function Interface library (required by WeasyPrint)
    #   libgdk-pixbuf2.0-dev: Development files for the GDK Pixbuf library (required by WeasyPrint)
    #   libjpeg-dev: Development files for JPEG image support (required by WeasyPrint)
    #   libpng-dev: Development files for PNG image support (required by WeasyPrint)
    #   zlib1g-dev: Development files for the zlib compression library (required by WeasyPrint)
    #   fonts-freefont-ttf: A common free font package (WeasyPrint needs fonts to render PDFs)
    apt-get upgrade -y --no-install-recommends && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libcairo2 \
    libgirepository-1.0-1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libsoup-3.0-0 \
    libffi-dev \
    libjpeg-dev \
    libopenjp2-7-dev \
    zlib1g-dev \
    fontconfig && rm -rf /var/lib/apt/lists/*


# Copy the project's requirements file into the container at the /app directory
COPY requirements.txt /app/

# Install Python dependencies from the requirements file
# --no-cache-dir: Prevents pip from caching packages, reducing image size
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project directory into the container at the /app directory
COPY . /app/

# Expose port 8000 to allow access to the Django development server from the host
EXPOSE 8000

# Define the command to run when the container starts
# This command starts the Django development server on all available interfaces (0.0.0.0) and port 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]