# Generated by Django 5.2.6 on 2025-09-13 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_usersubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='polar_price_id',
            field=models.CharField(blank=True, help_text='The Price ID from Polar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='polar_product_id',
            field=models.CharField(blank=True, help_text='The Product ID from Polar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='polar_subscription_id',
            field=models.CharField(blank=True, help_text='The Subscription ID from Polar', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
