# Generated by Django 5.2.6 on 2025-09-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_polar_price_id_plan_polar_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='polar_price_id',
        ),
    ]
