# Generated by Django 5.2.6 on 2025-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_polar_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
