# Generated by Django 5.2.6 on 2025-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='polar_customer_id',
            field=models.CharField(blank=True, help_text='The Customer ID from Polar', max_length=100, null=True),
        ),
    ]
