# Generated by Django 5.2.6 on 2025-09-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_usersubscription_polar_customer_id'),
        ('plans', '0007_auto_20250917_0400'),
    ]

    operations = [
    ]
